version: "3.8"

services: 

  nginx: 
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/www:/www
    ports:
      - 80:80

  portainer:
    image: portainer/portainer
    container_name: portainer
    hostname: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  api: 
    build: ./microservice
    # container_name: api
    hostname: api
    restart: always
    volumes:
      - ./microservice/scripts:/app
    ports:
      - 5000
    environment: 
      FLASK_APP: /app/script.py
    deploy:
      mode: replicated
      replicas: 2